### PR TITLE
Updated to work with the current version of Root-me

### PR DESCRIPTION
**Pull request by uN4sh**
+ Updated scraping regexes
+ Removed the progress bar for the score display (not relevant anymore)
+ Added a checkbox to use the Leader's number of challenges as the maximum value (for display purposes)

### CODE REVIEW

**Comment by mpgn** [comment]
Hello, thanks for the PR, can you post me a screenshot of the result ?

**Comment by uN4sh** [comment]
Of course, here it is!

Capture d'écran 2023-03-30 220728

**Comment by mpgn** [comment]
Code looks good, UI  looks good, I trust you 👍

**Comment by uN4sh** [comment]
Looking up the source code of the 2017 profile pages on the Wayback Machine to update the regexes was fun 😊

**Pull request merged**
